version: '3.4'

services:
  inkwell.api:
    image: ${DOCKER_REGISTRY-}inkwell.api
    build:
      context: .
      dockerfile: Inkwell.Api\Dockerfile
    ports:
      - "5050:80"

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local